name: GroupingPlugin
version: 1.1.0
main: com.github.mourthag.MainGroupingPlugin.Main
author: Mourthag
commands:
  party:
    aliases: [partyhelp]
    usage: /party
    description: List all commands for Groupingplugin
  partyInvite:
    aliases: [inv]
    usage: /partyInvite [player]
    description: Invite a player into your party
  partyCreate:
    aliases: [partycr]
    usage: /partyCreate
    description: Creates a private Party for you and your Friends
  partyLeave:
    aliases: [partylv]
    usage: /partyLeave
    description: Leave the current party
  partymsg:
    aliases: [p]
    usage: /partymsg <message>
    description: Sends a message to your party members
  partyAccept:
    aliases: [partyA]
    usage: /partyAccept
    description: Accepts the current Invite
  partyDecline:
    aliases: [partyD]
    usage: /declineInvite
    description: Declines the current Invite
  partyList:
    aliases: [list]
    usage: /partyList
    description: Lists all members of your Party
  partyKick:
    aliases: [pkick]
    usage: /partyKick [player]
    description: Kicks a player from your Party  