name: GroupingPlugin
version: 1.0.0
main: com.github.mourthag.MainGroupingPlugin.Main
author: Mourthag
commands:
  invite:
    aliases: [inv]
    usage: invite [player]
    description: Invite a player into your group
  createGroup:
    aliases: [crGroup]
    usage: createGroup
    description: Creates a private Group for you and your Friends
  leaveGroup:
    aliases: [lvGroup]
    usage: leaveGroup
    description: Leave the current group
  msgGroup:
    aliases: [p]
    usage: msgGroup <message>
    description: Sends a message to your Group members